name: "Deployment of website"
on:
    push:
        branches:
            - master

jobs:
    deployment:
        runs-on: self-hosted
        steps:
            - name: "Update System"
              run: sudo apt-get update

            - name: "Install Apache web server"
              run: sudo apt install apache2 -y 




                

            

            
            