name: site deployment
on:
    push:
        branches:
            - master
            - test
jobs:
    preparation:

        if: ${{ github.ref_name == 'test' }}
        runs-on: self-hosted
        steps:
            - name: print the github object
              env:
                WHATEVER: ${{ toJSON(github) }}
    
              run: echo $WHATEVER

            - name: checkout the repository
              uses: actions/checkout@v4

            - name: build Docker image for this website
              run: |
                sudo docker build -t simpleweb.com:$RANDOM .

            - name: Run the image as a container
              run: |
                sudo docker run -d -p 80:80 simpleweb.com:$RANDOM


            


        

