name: site deployment
on:
    push:
        branches:
            - master
jobs:
    preparation:
        runs-on: self-hosted

        steps:
            - name: checkout the repository
              uses: actions/checkout@v4
              
            - name: run a bunch of scripts
              run: bash runscript.sh 


        

