name: site deployment
on:
    push:
        branches:
            - master
            - test
            - destroy
jobs:
    setup:

        if: ${{ github.ref_name == 'test' }}
        runs-on: self-hosted
        steps:
            - name: print the github object
              env:
                WHATEVER: ${{ toJSON(github) }}
    
              run: echo $WHATEVER

            - name: checkout from the repository
              uses: actions/checkout@v4

            - name: Build image from Dockerfile
              run: | 
                
                sudo docker build -t theoafactor/cyclobold:latest .

            - name: Run the image as a container
              run: |
                sudo  docker run -d -p 80:80 --name cyclobold theoafactor/cyclobold:latest

     

    cleanup:
        if: ${{ github.ref_name == 'destroy' }}
        runs-on: self-hosted
        steps:
      
            - name: checkout from the repository
              uses: actions/checkout@v4

            - name: list directory
              run: ls 

            - name: "Initialize the terraform"
              run: |
                terraform init

            - name: setup aws cli
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-region: "eu-west-2"
                aws-secret-access-key: ${{ secrets.AWS_SECRET }}
                

            - name: Apply Terraform
              run: |
                  cd ~
                  terraform destroy --auto-approve

              


                


            


        

