name: site deployment
on:
    push:
        branches:
            - master
            - test
            - destroy
jobs:
    setup:

        if: ${{ github.ref_name == 'test' }}
        runs-on: self-hosted
        steps:
            - name: print the github object
              env:
                WHATEVER: ${{ toJSON(github) }}
    
              run: echo $WHATEVER

            - name: checkout from the repository
              uses: actions/checkout@v4

            - name: Install Terraform
              run: bash _devops/install_terraform.sh

            - name: setup aws cli
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-region: "eu-west-2"
                aws-secret-access-key: ${{ secrets.AWS_SECRET }}

            - name: cleanup all files
              run: | 
                sudo rm -f *.pem
                
            - name: "Initialize the terraform"
              run: |
                  terraform init
                  
            - name: Apply Terraform
              run: |
                  terraform apply --auto-approve



    cleanup:
        if: ${{ github.ref_name == 'destroy' }}
        runs-on: self-hosted
        steps:
      
            - name: checkout from the repository
              uses: actions/checkout@v4

            - name: Install Terraform
              run: bash _devops/install_terraform.sh

            - name: setup aws cli
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-region: "eu-west-2"
                aws-secret-access-key: ${{ secrets.AWS_SECRET }}
                

            - name: Apply Terraform
              run: |
                  terraform destroy --auto-approve

              


                


            


        

