name: CI/CD Pipeline

on:
    push:
        branches:
            - main
            
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Build Docker image
              run: | 
                sudo docker build -t myapp:latest .        
  
            - name: Stop and remove old container (if exists)
              run: |
                sudo docker rm -f myapp || true

            - name: Run Docker container
              run: |
                  sudo docker run -d -p 80:80 --name myapp myapp:latest

              


                


            


        

