name: "Deployment of website"
on:
    push:
        branches:
            - master

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: "Update the machine"
              run: sudo apt-get update

            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "Install and Configure Kubectl"
              uses: azure/setup-kubectl@v3
              with:
                version: '1.29' # default is latest stable
              id: install

            - name: "Configure AWS Credentials"
              uses: aws-actions/configure-aws-credentials@v1
              with: 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET }}
                aws-region: eu-west-2

            - name: "Login to Docker Hub"
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: "Setup environmental variables and build"
              env: 
                USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                IMAGE_TAG: $USERNAME/simpleweb:v1
              run: |
                docker build -t $IMAGE_TAG .
                docker push $IMAGE_TAG


                

            

            
            