name: Deployment Workflow
on:
  push:
    branches:
      - master
  
jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: preparation
        run: echo "Preparing to deploy ..."
    
      - name: checks out the repository
        uses: actions/checkout@v4
      

    