name: "Get Image and Build"
on:
  workflow_run:
    workflows: ["Deployment Workflow"]
    types:
        - completed
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: preparation
        run: echo "Preparing to build ..."
    
      - name: pull the image from docker hub
        run: sudo docker pull theoafactor/simplepersonal101:latest

      - name: "Delete the old image"
        run: sudo docker rm -f simplepersonal101 || true

      - name: "Run the docker image"
        run: "sudo docker run -d 8080:8080 --name simplepersonal101 simplepersonal101:latest"
       
    

        

          

    